### PR TITLE
Fixes a couple of bugs on RawSocketWebSocketClient

### LINKED ISSUE #70: WebSocketClient hang
Reported by Oleg on slack:

```kotlin
fun testMe() = run < Unit > {
    var conn: WebSocketClient
    val j = GlobalScope.launch {
        conn = WebSocketClient("ws://MINI:22237", null, null, "", false)
    }
    GlobalScope.launch {
        println("wait conn")
        j.join()
        println("finish wait conn")
    }
}
```

As I understood `finish wait conn` is not printed.

### PR DESCRIPTION
**Pull request by soywiz**
Fixes #70 
Happened with `org.java-websocket:Java-WebSocket:1.5.1`

### CODE REVIEW

File: korio/src/commonMain/kotlin/com/soywiz/korio/net/ws/RawSocketWebSocketClient.kt [hunk 1]
```diff
@@ -97,9 +97,11 @@ class RawSocketWebSocketClient(
             add("Sec-WebSocket-Version: 13")
             add("Connection: Upgrade")
             add("Sec-WebSocket-Key: ${key.toByteArray().toBase64()}")
-            add("Origin: $origin")
+            if (origin != null) {
+                add("Origin: $origin")
+            }
             add("User-Agent: ${HttpClient.DEFAULT_USER_AGENT}")
-        }.joinToString("\r\n") + "\r\n\n").toByteArray())
+        }.joinToString("\r\n") + "\r\n\r\n").toByteArray())
```
Comment (soywiz) [inline korio/src/commonMain/kotlin/com/soywiz/korio/net/ws/RawSocketWebSocketClient.kt:104]: This was the line that was causing the issue. The server expected `\r\n\r\n` and due to a typo missing the `\r` the websocket server thought the request was not completed

File: korio/src/commonMain/kotlin/com/soywiz/korio/net/ws/RawSocketWebSocketClient.kt [hunk 2]
```diff
@@ -111,37 +113,35 @@ class RawSocketWebSocketClient(
...
-                            WsOpcode.Pong -> {
-                                lastPong = DateTime.now()
-                            }
-                            else -> {
-                                when (payload) {
-                                    is String -> onStringMessage(payload)
-                                    is ByteArray -> onBinaryMessage(payload)
-                                }
-                                onAnyMessage(payload)
+        launchImmediately(coroutineContext) {
```
Comment (soywiz) [inline korio/src/commonMain/kotlin/com/soywiz/korio/net/ws/RawSocketWebSocketClient.kt:116]: Additionally the `coroutineScope` prevented this from terminating
